### ISSUE TITLE
Why do the following errors occur?How?

### ISSUE THREAD

**Issue by monkeystrive** [hfawaz/aaltd18#8]
![image](https://user-images.githubusercontent.com/39188611/79071923-d5e93280-7d10-11ea-8ef7-be38ca181829.png)

**Comment by monkeystrive** [comment]
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from utils.constants import UNIVARIATE_ARCHIVE_NAMES as ARCHIVE_NAMES
  File "/opt/module/datas/tsc_data_augment/utils/constants.py", line 3, in <module>
    from distances.dtw.dtw import dynamic_time_warping as dtw
ModuleNotFoundError: No module named 'distances.dtw.dtw'

**Comment by hfawaz** [comment]
This is due to not running the cython script in [utils/build-cython.sh](https://github.com/hfawaz/aaltd18/blob/master/utils/build-cython.sh)
