### ISSUE TITLE
Why do the following errors occur?How?

### ISSUE THREAD

**Issue by monkeystrive** [hfawaz/aaltd18#9]
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from utils.constants import UNIVARIATE_ARCHIVE_NAMES as ARCHIVE_NAMES
  File "/opt/module/datas/tsc_data_augment/utils/constants.py", line 3, in <module>
    from distances.dtw.dtw import dynamic_time_warping as dtw
ModuleNotFoundError: No module named 'distances.dtw.dtw'

**Comment by yyhhhjnjvgcx** [comment]
Is it resolved please?
